os: linux
dist: xenial
language: php

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction
  - yarn install
script:
  - yarn dev
  - php bin/phpunit