language: php

php:
  - 8.1

cache:
  yarn: true
  directories:
      - node_modules
      - .phpunit
      - ~/php-ext

before_install:
  - composer self-update
  - yarn install --ignore-engines
  - yarn dev

install:
  - composer update --no-progress

script:
  - ./bin/phpunit