language: php

dist: bionic

git:
    depth: 1

addons:
    apt_packages:
        - yarn

matrix:
    include:
        - php: 8.1
    fast_finish: true

cache:
  yarn: true
  directories:
      - .phpunit
      - ~/php-ext

before_install:
  composer self-update

install:
  - composer update --no-progress
  
script:
  - ./bin/phpunit