os: linux
dist: xenial
language: php
  php: 
    8.1.5
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache

install:
  - composer update
  - yarn install
script:
  - yarn dev
  - php bin/phpunit